const { Plane } = require('../models')

const planedata = [
    {
        user_id: 1,
        rental_id: 2,
        pilot_id: 3,
        airport_id: 4,
        type_of_plane: "Global 6000",
        seats: 17,
        total_payload: '5,770lbs',
        range: '6,000nm',
        flight_attendant: true,
        wifi: true,
    },
    {
        user_id: 2,
        rental_id: 1,
        pilot_id: 1,
        type_of_plane: "G650 Gulfstream",
        seats: 13,
        total_payload: '6,500lbs',
        range: '7000nm',
        flight_attendant: true,
        wifi: true,
    },
    {
        user_id: 5,
        rental_id: 3,
        pilot_id: 4,
        type_of_plane: "Phenom-300X",
        seats: 10,
        total_payload: '2,637lbs',
        range: '2,200nm',
        flight_attendant: true,
        wifi: true,
    },
    {
        user_id: 6,
        rental_id: 1,
        pilot_id: 8,
        type_of_plane: "Citation M2 Gen2",
        seats: 7,
        total_payload: '1,500lbs',
        range: '1,550nm',
        flight_attendant: false,
        wifi: true,
    },
    {
        user_id: 9,
        rental_id: 2,
        pilot_id: 7,
        type_of_plane: "Falcon 2000 LXS",
        seats: 10,
        total_payload: '2,600lbs',
        range: '4,000nm',
        flight_attendant: true,
        wifi: true,
    }, 
    {
        user_id: 8,
        rental_id: 2,
        pilot_id: 10,
        type_of_plane: "Hawker 4000",
        seats: 8,
        total_payload: '2,525lbs',
        range: '3,341nm',
        flight_attendant: true,
        wifi: true,
    },
    {
        user_id: 6,
        rental_id: 1,
        pilot_id: 11,
        type_of_plane: "Learjet75",
        seats: 8,
        total_payload: '1000lbs',
        range: '2,026nm',
        flight_attendant: false,
        wifi: true,
    },
    {
        user_id: 5,
        rental_id: 2,
        pilot_id: 6,
        type_of_plane: "Falcon 900LX",
        seats: 14,
        total_payload: '3,500lbs',
        range: '4,750nm',
        flight_attendant: true,
        wifi: true,
    },

    
];

const seedPlane = () => Plane.bulkCreate(planedata);

module.exports = seedPlane;